build-vendor-image:
  image: docker:latest
  stage: build
  when: manual
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - docker build --pull -t murew-vendor:alpha1 .
    - docker save -o murew-vendor.tar murew-vendor:alpha1
    - docker push murew-vendor:alpha1
  except:
    - master
  artifacts:
    paths:
    - murew-vendor.tar