build-vendor-image:
  image: docker:latest
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - docker build -t murew-vendor:alpha1 -f vendor_apps.dockerfile .
    - docker save -o murew-vendor.tar murew-vendor:alpha1
  except:
    - master
  artifacts:
    paths:
    - murew-vendor.tar

build-distance-helper-image:
  image: docker:latest
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - docker build -t distance-helper:lastest -f distance_helper.dockerfile .
    - docker save -o distance-helper.tar distance-helper:lastest
  except:
    - master
  artifacts:
    paths:
    - distance-helper.tar

build-emailagent-image:
  image: docker:latest
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - docker build -t emailagent:lastest -f emailagent.dockerfile .
    - docker save -o emailagent.tar emailagent:lastest
  except:
    - master
  artifacts:
    paths:
    - emailagent.tar